//全局管理
export const NAV_CHANGE_TYPE = 'NAV_CHANGE_TYPE' //路由切换样式

//登录&注册
export const REGISTER_SEND_CODE = 'REGISTER_SEND_CODE' //注册发送验证码
export const REGISTER_GEETEST_INIT = 'REGISTER_GEETEST_INIT' //极验初始化
export const REGISTER_GEETEST_SWITCH = 'REGISTER_GEETEST_SWITCH'//极验开关

//新注册，推广注册活动
export const PROMOTE_REGISTER_SEND_CODE = 'PROMOTE_REGISTER_SEND_CODE' //发送验证码
export const PROMOTE_REGISTER_VALI_CODE = 'PROMOTE_REGISTER_VALI_CODE' //验证验证码
export const PROMOTE_VALI_IDCARD_NEXT = 'PROMOTE_VALI_IDCARD_NEXT' //验证身份证下一步
export const PROMOTE_IMAGE_UPLOAD = 'PROMOTE_IMAGE_UPLOAD' //推广上传照片
export const PROMOTE_REGISTER = 'PROMOTE_REGISTER' //推广最终注册
export const PROMOTE_STEP_CHANGE = 'PROMOTE_STEP_CHANGE' //推广注册步骤切换
export const PROMOTE_GEOLOCATION_UPDATE = 'PROMOTE_GEOLOCATION_UPDATE'  //获取地理位置更新

//商户注册
export const MERCHANT_REGISTER_SEND_CODE = 'MERCHANT_REGISTER_SEND_CODE' //发送验证码
export const MERCHANT_REGISTER_VALI_CODE = 'MERCHANT_REGISTER_VALI_CODE' //验证验证码
export const MERCHANT_VALI_IDCARD_NEXT = 'MERCHANT_VALI_IDCARD_NEXT' //验证身份证下一步
export const MERCHANT_IMAGE_UPLOAD = 'MERCHANT_IMAGE_UPLOAD' //商户上传
export const MERCHANT_REGISTER = 'MERCHANT_REGISTER' //商户最终注册
export const MERCHANT_STEP_CHANGE = 'MERCHANT_STEP_CHANGE' //商户注册步骤切换
export const MERCHANT_GEOLOCATION_UPDATE = 'MERCHANT_GEOLOCATION_UPDATE'  //获取地理位置更新
export const MERCHANT_REGISTER_TYPE_CHANGE = 'MERCHANT_REGISTER_TYPE_CHANGE' //设置注册类型




//一般通用部分
export const NEWS_ITEM = 'NEWS_ITEM' //新闻详情信息
export const ACTIVITY_SHOW_IMG = 'ACTIVITY_SHOW_IMG' //普通展示新闻展示图片
export const INVITE_RED_PACKET_INFO = 'INVITE_RED_PACKET_INFO' //邀请记录统计
export const INVITE_RED_PACKET_TOTAL = 'INVITE_RED_PACKET_TOTAL' //邀请总人数
export const INVITE_RED_PACKET_LIST = 'INVITE_RED_PACKET_LIST' //邀请人数集合


//固定不变部分
export const LOAN_AGREEMENT = 'LOAN_AGREEMENT'  //借款协议

//服务
export const CUSTOMER_SERVICE_ENQUIRE = 'CUSTOMER_SERVICE_ENQUIRE' //询问是否可以连接
export const CUSTOMER_SERVER_RECEIVE = 'CUSTOMER_SERVER_RECEIVE' //收到服务器推送消息
export const CUSTOMER_SERVICE_CONNECT_STATUS = 'CUSTOMER_SERVICE_CONNECT_STATUS' //连接状态改变
export const CUSTOMER_SERVICE_HISTORY_RECORDS = 'CUSTOMER_SERVICE_HISTORY_RECORDS'  //获取更多消息
export const CUSTOMER_SERVICE_UPLOAD_IMAGE = 'CUSTOMER_SERVICE_UPLOAD_IMAGE' //上传图片


//产品相关
export const PRODUCT_INFO = 'PRODUCT_INFO' //产品详情，根据产品id获取产品详情


